name = "ligma-personaleventplanner"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-11-25"
compatibility_flags = ["nodejs_compat"]
[vars]
NEXT_PUBLIC_FIREBASE_API_KEY = "AlzaSyATu0GiahKhqmpyTaxUo1uSqsO0DppghGg"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "ligma-personaleventplanner.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "ligma-personaleventplanner"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "ligma-personaleventplanner.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "66250269201"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:66250269201:web:c13ce91a58ae0d50f647b0"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-82BB3BME5H"